version: 2

models:
  - name: stg_users
    description: "users table containing customer information"
    columns:
      - name: user_id
        description: "The primary key for users table - unique identifier for each user"
        data_tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: bigint
      

      - name: full_name
        description: "The full name of the user"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: varchar

      - name: email
        description: "The email of the user"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: varchar
          - dbt_expectations.expect_column_values_to_match_regex:
              arguments:
                regex: '(?i)^NULL$|.*@.*'
      
      - name: signup_date
        description: "The date when the user signed up"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: date

      - name: region
        description: "The region of the user"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: varchar
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments:
                value_set: ['north', 'east', 'west', 'south']
  
  - name: stg_orders
    description: "The orders table containing order information"
    columns:
      - name: order_id
        description: "The primary key for orders table"
        data_tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: bigint

      - name: user_id
        description: "The foreign key to the users table"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: bigint
      
      - name: product_id
        description: "The foreign key to the products table"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: bigint
      
      - name: order_date
        description: "The date when the order was placed"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: date
      
      - name: quantity
        description: "The quantity of the product ordered"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: integer

  
  - name: stg_products
    description: "products table"
    columns:
      - name: product_id
        description: "The primary key for products table"
        data_tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: bigint
      
      - name: product_name
        description: "The name of the product"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: varchar
      
      - name: category
        description: "The category of the product"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: varchar
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments:
                value_set: ['electronics', 'clothing', 'home']

  
  - name: stg_promotions
    description: "promotions table"
    columns:
      - name: promotion_id
        description: "The primary key for promotions table"
        data_tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: bigint
      
      - name: promotion_code
        description: "The name of the promotion"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: varchar
      
      - name: discount_percentage
        description: "The discount percentage of the promotion"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: bigint
          
