version: 2

models:
  - name: fct_orders
    description: "fact orders table"
    columns:
      - name: order_id
        description: "The primary key for fact orders table"
        data_tests:
          - unique
          - not_null
  
 